### ISSUE TITLE
Is there command to view multiple committer

### ISSUE THREAD

**Issue by zero41120** [james-stoup/heatwave#2]
I have 2 accounts on 2 systems. They are not using the same credential but both commit to the same project. I would like to see if we can do
heatwave . "AAA, BBB" and combine both AAA and BBB's heatmap together

**Comment by james-stoup** [comment]
So you want the heat map of two users? For example, if you have 10 users you want to to see the combined heat map of user 4 and user 9? If that's what you are looking for, I could probably give that a shot.

**Comment by zero41120** [comment]
@james-stoup 
That is correct for my use case. 
But it will be great to support any number of users.

**Comment by james-stoup** [comment]
@zero41120 Ok, your feature has been added. I haven't pushed this up to pip yet, so for the moment you'll have to just build it yourself.

**Comment by james-stoup** [comment]
@zero41120 

So pip has been updated so you should be able to upgrade this from pip now.
