### ISSUE TITLE
Customise the commit quantity legend 

### ISSUE THREAD

**Issue by oflynned** [james-stoup/heatwave#3]
I generally make up to 50+ commits in a day depending on workload, so a legend showing 5+ as a colour isn't overly informative. Instead, I would love to pass in a config of how to divide the legend colours, and parse data depending on that. 

It would also be awesome if it could be divided into some steps from the statistical frequency instead of hardcoding step levels, and parsed depending on where it fits in the cumulative frequency of how often someone commits on average.

I can create a PR in the next while if this is no longer being actively developed 🚀

**Comment by james-stoup** [comment]
@oflynned I can probably add an offset option that would allow you to breaking the steps up by a multiple. So if you used --off-set = 10 then your breakdown would be 0, 1-10, 11-20, 21-30, 31-40, 41+

I had never remotely thought of doing this so I'm going have to have to rework how the colors are handled but I should be able to get this done soon.

As for your other request, I'm not totally sure what you want. If you could give me more details I'll look into it. If you just want to do it yourself I'm happy to merge in anything you want to contribute.

**Comment by james-stoup** [comment]
@oflynned 

I added in the offset feature, test it out and see if that works for you. I'll need more details on the second issue you had.

**Comment by oflynned** [comment]
@james-stoup Awesome! I'll take a look at that later today.

Regarding the second feature, I realise I didn't explain it well enough. I just meant it could be interesting seeing if instead of passing in a config, a quick statistical model of the commit count can be generated (since we have the daily sum, frequency and distribution at hand) and generate the steps automatically. It could be as simple as taking the max commit count over the time range, and then creating a step as `max / step count`. Or alternatively take the frequency as it's more likely that the commit count could follow some form of normal distribution and take the count as a percentage of the area under the curve. 

Just some ideas as I think the repo here is a great idea. Of course it could be overkill, but I think people who want to see their commit history visualised in a terminal tend to want to have the same or more control than that of what GitHub offers.
